### ISSUE TITLE
Bug: image plate not possible to place without sg magnet on macro scene

### ISSUE THREAD

**Issue by aaronpostus** [game-based-learning/stern-gerlach-sim#24]

**Comment by joshvarg** [comment]
**:warning:Though now functional, this fix needs to be revisited for a more robust solution under a future refactor.:warning:**
# Intended Behaviour

In the classical magnet scene, there is an option to place a Large Image Plate as the first node.

# Bug

Upon click nothing would happen and the dialog would close.

# Solution

Commented out a guard in `NodeBuilder.PlaceImagePlate` that would return if `factory.SilverAtomMode()` and the current node's parent being source were both true.

Modified `NodeBuilder.PlaceLargePlateNodes` such that the main logic is now wrapped in an if-elseif clause with the if being the default case and else if accounting for the first node case.
